feat: tv, remove unused plugins, use mini, add snippets

diff --git a/dotfiles/scripts/.local/bin/scripts/tmux-sessionizer b/dotfiles/scripts/.local/bin/scripts/tmux-sessionizer
--- a/dotfiles/scripts/.local/bin/scripts/tmux-sessionizer
+++ b/dotfiles/scripts/.local/bin/scripts/tmux-sessionizer
@@ -1,15 +1,12 @@
 #!/usr/bin/env bash
 
-if [[ $# -eq 1 ]]; then
-  selected=$1
+if command -v tv &>/dev/null && [ -z "$1" ]; then
+  selected=$(tv git-repos)
+elif ! command -v fd &>/dev/null; then
+  echo "fd not found"
+  selected=$(find "$HOME"/dev/ "$HOME"/work/ "$HOME" -type d -mindepth 1 -maxdepth 2 | fzf)
 else
-  if ! command -v fd &> /dev/null
-  then 
-    echo "fd not found"
-    selected=$(find $HOME/dev/ $HOME/work/ $HOME -type d -mindepth 1 -maxdepth 2 | fzf)
-  else
-    selected=$(fd --max-depth 2 --type d . "$HOME/dev" "$HOME/work" "$HOME" | fzf)
-  fi
+  selected=$(fd --max-depth 2 --type d . "$HOME/dev" "$HOME/work" "$HOME" | fzf)
 fi
 
 if [[ -z $selected ]]; then
@@ -20,15 +17,15 @@ selected_name=$(basename "$selected" | tr . _)
 tmux_running=$(pgrep tmux)
 
 if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
-    tmux new-session -s $selected_name -c $selected
-    exit 0
+  tmux new-session -s "$selected_name" -c "$selected"
+  exit 0
 fi
 
-if ! tmux has-session -t=$selected_name 2> /dev/null; then
-    tmux new-session -ds $selected_name -c $selected
+if ! tmux has-session -t="$selected_name" 2>/dev/null; then
+  tmux new-session -ds "$selected_name" -c "$selected"
 fi
 
-tmux switch-client -t $selected_name 2> /dev/null
+tmux switch-client -t "$selected_name" 2>/dev/null
 if [ $? -ne 0 ]; then
-  tmux attach -t $selected_name 2> /dev/null
+  tmux attach -t "$selected_name" 2>/dev/null
 fi
